outputs:
##  True or False
  access_file: false
  report: true
  fixity:
    check_fixity: true
    check_stream_fixity: true
    embed_stream_fixity: false
    output_fixity: false
    overwrite_stream_fixity: false
# preferred qctools extension. qct-parse requires qctools.xml.gz
  qctools_ext: qctools.xml.gz
tools:
  exiftool:
##  True or False
    check_exiftool: true
    run_exiftool: true
  ffprobe:
##  True or False
    check_ffprobe: true
    run_ffprobe: true
  mediaconch:
##  mediaconch policy file name from any xml file in the config directory
    mediaconch_policy: JPC_AV_NTSC_MKV_2024-07-31.xml
##  True or False
    run_mediaconch: true
  mediainfo:
##  True or False
    check_mediainfo: true
    run_mediainfo: true
    run_mediatrace: true
  mediatrace:
##  True or False
    check_mediatrace: true
    run_mediatrace: false
  qctools:
##  True or False
    check_qctools: true
    run_qctools: true
  qct-parse:
##  barsDetection can be true or left empty (null)
    barsDetection: true
##  evaluateBars can be true or left empty (null)
    evaluateBars: true
##  choose a profile from the list from config.yaml in the qct-parse[content] section
## 'contentFilter' format:
##    - allBlack
    contentFilter:
    profile:
##  choose a tag from the list from config.yaml in the qct-parse[fullTagList] section
## 'tagname' format:
##    - [YMIN, lt, 100] 
    tagname:
##  barsDetection can be true or left empty (null)
    thumbExport: true
